# Generated by Django 2.1.5 on 2019-02-10 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstudy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('app_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workstudy.AppData')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1000)),
                ('supervisor', models.CharField(max_length=256)),
                ('supervisor_email', models.CharField(max_length=256)),
                ('supervisor_phone', models.CharField(max_length=256)),
                ('second_contact', models.CharField(max_length=256)),
                ('second_contact_email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=100)),
                ('personal_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workstudy.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=100)),
                ('personal_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workstudy.PersonalInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='availability',
            name='app_data',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
