# Generated by Django 2.1.5 on 2019-02-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstudy', '0004_auto_20190211_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appavailability',
            name='semester',
        ),
        migrations.AddField(
            model_name='siteavailability',
            name='site_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workstudy.SiteInfo'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='site_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workstudy.SiteInfo'),
        ),
    ]
