# Generated by Django 2.1.5 on 2019-02-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstudy', '0006_auto_20190215_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='phone_num',
            field=models.CharField(max_length=256),
        ),
    ]
