# Generated by Django 2.1.5 on 2019-02-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstudy', '0009_auto_20190219_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='perferred_name',
        ),
        migrations.AddField(
            model_name='appdata',
            name='for_class',
            field=models.NullBooleanField(verbose_name='Is this for a class?'),
        ),
        migrations.AddField(
            model_name='appdata',
            name='what_class',
            field=models.CharField(max_length=256, null=True, verbose_name='If so, what class is it for?'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='preferred_name',
            field=models.CharField(default=models.CharField(max_length=256, verbose_name='First Name'), max_length=256, verbose_name='Preferred Name'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='pronouns',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='started',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='car',
            field=models.NullBooleanField(verbose_name='Do you have a car?'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='carpool',
            field=models.NullBooleanField(verbose_name='Are you willing to be a carpool driver?'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='ccec_ws',
            field=models.NullBooleanField(verbose_name='Have you previously worked through the CCEC?'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='clearances',
            field=models.NullBooleanField(verbose_name='Do you have clearances? (Child Abuse, FBI Fingerprints, State Police)'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='foreign_lang',
            field=models.NullBooleanField(verbose_name='Are you fluent in a foreign language?'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='grad_month',
            field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default='May', max_length=256, verbose_name='Graduation Month'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appdata',
            name='hear_about_ccec',
            field=models.CharField(max_length=256, null=True, verbose_name='How did you hear about the CCEC?'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='keep_schedule',
            field=models.NullBooleanField(verbose_name='Would you like to keep your same schedule?'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='languages',
            field=models.CharField(max_length=256, null=True, verbose_name='What languages?'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='phone_num',
            field=models.CharField(max_length=256, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='previous_site',
            field=models.CharField(max_length=256, null=True, verbose_name='If so, what site did you work at?'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='remain_at_site',
            field=models.NullBooleanField(verbose_name='Would you like to remain at your current site?'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='semester',
            field=models.CharField(max_length=100, verbose_name="Semester (example: 'Spring 2019' or 'Fall 2018' )"),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='wanted_hours',
            field=models.IntegerField(verbose_name='How many total hours a week would you like to work?'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='work_study',
            field=models.NullBooleanField(verbose_name='Do you qualify for federal work study?'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='siteplacementrank',
            name='after_school',
            field=models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6')], null=True, verbose_name='After School'),
        ),
        migrations.AlterField(
            model_name='siteplacementrank',
            name='charity_org',
            field=models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6')], null=True, verbose_name='Charity Organization'),
        ),
        migrations.AlterField(
            model_name='siteplacementrank',
            name='community_center',
            field=models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6')], null=True, verbose_name='Community Center'),
        ),
        migrations.AlterField(
            model_name='siteplacementrank',
            name='hospice',
            field=models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6')], null=True),
        ),
        migrations.AlterField(
            model_name='siteplacementrank',
            name='medical',
            field=models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6')], null=True),
        ),
        migrations.AlterField(
            model_name='siteplacementrank',
            name='other',
            field=models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6')], null=True),
        ),
    ]
