# Generated by Django 2.1.5 on 2019-02-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstudy', '0010_auto_20190226_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='preferred_name',
            field=models.CharField(max_length=256, verbose_name='Preferred Name'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='pronouns',
            field=models.CharField(max_length=256),
        ),
    ]
