# Generated by Django 2.1.5 on 2019-03-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstudy', '0011_auto_20190226_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteplacementrank',
            name='after_school',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True, verbose_name='After School'),
        ),
        migrations.AlterField(
            model_name='siteplacementrank',
            name='charity_org',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True, verbose_name='Charity Organization'),
        ),
        migrations.AlterField(
            model_name='siteplacementrank',
            name='community_center',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True, verbose_name='Community Center'),
        ),
        migrations.AlterField(
            model_name='siteplacementrank',
            name='hospice',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='siteplacementrank',
            name='medical',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='siteplacementrank',
            name='other',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True),
        ),
    ]
