# Generated by Django 2.1.5 on 2019-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstudy', '0013_auto_20190331_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appavailability',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='appavailability',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Start Time'),
        ),
    ]
