# Generated by Django 2.1.5 on 2019-04-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstudy', '0014_auto_20190410_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteavailability',
            name='site_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workstudy.SiteInfo'),
        ),
        migrations.AlterField(
            model_name='siteavailability',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='siteavailability',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studentschedule',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studentschedule',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
